### ISSUE TITLE
l.loadModel is not a function - tfjs 1.1.2

### ISSUE THREAD

**Issue by lefnire** [shaqian/tfjs-yolo#3]
```
"@tensorflow/tfjs": "^1.1.2",
"tfjs-yolo": "^0.0.3",
```

I get `l.loadModel is not a function`, same issue as https://github.com/ModelDepot/tfjs-yolo-tiny/pull/22. If I patch per that PR (use `loadLayersModel`) I get `myYolo.predict is not a function`. I actually tried pinning tfjs back to `^1.0.0`, but I get the same errors (strangely, since this project is pinned at that version..)

**Comment by shaqian** [comment]
I think it's fixed in https://github.com/shaqian/tfjs-yolo/pull/2. I just published the change in v0.0.4.

**Comment by lefnire** [comment]
confirmed fixed, thanks!
